### ISSUE TITLE
Replace wercker in the toolchain with suitable alternative

### ISSUE THREAD

**Issue by KrisBuytaert** [devopsdays/devopsdays-web#157] opened 2016-04-22 13:47 UTC
@mattstratton  had some technical reasons for this .. so we might want to document them so we can use these requirements in selecting an alternative .

**Comment by mattstratton** [comment] 2016-04-22 14:19
Absolutely! The only reason I am tied to wercker right now is a) it works, b) it's what I use on other hugo sites with great regularity so I didn't have to reinvent the wheel, and c) there is excellent support on this workflow (hugo to wercker to GH Pages) in the hugo community :)

Requirements-wise, here's what we need out of any replacement build tool for the site:

## Must-have

* Ability to publish to GH Pages 
* No "single owner" account for the tool (similar to having multiple admins/editors in GH teams/repos, we need to have multiple people able to re-kick builds/deploys)
* Hook into a test for a PR (I am using the wrong words, but with our workflow today, when a PR is submitted, wercker tries to build it and the PR itself contains the result of that test build, so that the PR reviewer at least knows that it didn't break the build)

## "Nice to have"
* Prior art/documents from folks who have done exactly this within Hugo (today, when I have issues with my deploys in this workflow, [there are active Hugo users who do the same thing](https://discuss.gohugo.io/t/automated-hugo-deployments-anywhere-using-wercker/539) and can help troubleshoot it)
* Slack notification integration (it would be nice to have build status messages sent to the #website channel on slack so folks can know if their deploy was successful after the PR was merged)
* Ability to use existing auth tool such as GH auth just so there is one less login to manage (although it should be optional for the user for people who don't like to have apps get access to their other GH stuff because GH auth granularity is sucky)

Right now these are the main ones - I reserve the right to think of a few more after reviewing it further. After the cutover, we will be making sure we have issues logged for everything and will review/prioritize the issues tagged for "Future Enhancements" for specific release cycles.

**Comment by mattstratton** [comment] 2016-08-10 19:55
Based on #824, we might consider migrating the whole shebang to Netlify - both the build and the hosting.

https://www.netlify.com/blog/2016/08/02/migrating-from-github-pages

**Comment by mattstratton** [comment] 2016-08-10 19:59
Netlify [supports redirects](https://www.netlify.com/docs/redirects), so we could always put the legacy stuff on s3 hosted at http://legacy.devopsdayso.org and write redirects wherein requests to `/events/2014/*`, etc, go there instead.

**Comment by mattstratton** [comment] 2016-08-10 20:16
Moving to Netlify would also handle #642.

One downside - it seems (this is anecdotal) that the large number of files used in our site is dragging down Netlify builds; I have one running over ten minutes at this point.

**Comment by mattstratton** [comment] 2016-08-10 20:18
We need to do some code cleanup as well - it's forcing some URL's to baseurl a certain way, if you take a look at this preview:

http://57ab87d7d6865d1672ba531f.paratrooper-sum-25346.netlify.com/

And click on a city name, you'll see it takes you to the `www.devopsdays.org` version of the site. It is possible to call `hugo` with a parameter to take in a different config file, but that wouldn't work because the URL changes on every build.

**Comment by mattstratton** [comment] 2016-08-11 01:06
So I figured out how to fix it up. First of all, thanks to @jfrazelle, I was able to get the PR checks to work (so this is live and working now with all NEW pull requests).

I also solved for the `baseURL` thing - there is an environment variable available in Netlify called `URL` which is the URL for the deployed site (in this case, the temporary one for the build). By passing `--baseURL URL` to the build, it seems to work now. This can be confirmed at http://deploy-preview-829.paratrooper-sum-25346.netlify.com/

**Comment by mattstratton** [comment] 2016-08-11 01:07
I'm guessing that Netlify is smart enough to not over-write multiple PR's, but I guess we'll find out...

**Comment by calavera** [comment] 2016-08-11 02:16
@mattstratton each pull request gets its own subdomain `deploy-preview-PR-ID...`. You're fine as long as you don't use the same PR for everything :laughing: 

PS: sorry for being a rando in the middle of this thread. Let me know if you need help with anything Netlify related, super happy to assist.

**Comment by mattstratton** [comment] 2016-08-12 15:17
Ihey @calavera - turns out I was totally wrong about firing in the `URL` environment variable in the `--baseURL` flag in my build command. It's not causing an issue here...well, not yet (there's only two small places we use `BaseURL` right now), but I'm seeing it in other places. Can you help me figure out how to access environment variables in the build command?

**Comment by mattstratton** [comment] 2016-08-12 15:31
For some additional clarity...on Twitter I learned that you have to prepend the variable with `$`, so `$URL` works. Except that it returns the URL of the "site", not the preview, so it doesn't seem to help with deploy previews.

**Comment by calavera** [comment] 2016-08-12 17:47
@mattstratton we'll have a fix for that very soon. I just added `DEPLOY_PRIME_URL` to the environment that contains the deploy preview URL. I'll ping you here in a few minutes when it's rolled out.

**Comment by calavera** [comment] 2016-08-12 18:10
@mattstratton new builds should have now that `DEPLOY_PRIME_URL` in the environment. Like with the `$URL`, you need the `$` prefix `$DEPLOY_PRIME_URL`. Unfortunately, we cannot change the value of `$URL` for now, I'm certain that people use it, and we need to double check the impact of it.

**Comment by mattstratton** [comment] 2016-08-12 18:38
Thanks @calavera! I'll test this out in a bit when I'm on a terminal. I think it's fine to have it be the separate variable name (if I am understanding properly how it will work) and I appreciate the help!

**Comment by mattstratton** [comment] 2016-08-15 12:49
So it sorta works. I think that the better solution is to change our setting for BaseURL to just "/" as recommended in a different thread. It just varies too much.

**Comment by mattstratton** [comment] 2016-08-15 12:52
Yep. That seemed to work.

**Comment by mattstratton** [comment] 2016-08-15 22:54
The work for the Netlify migration is being tracked in #854

**Comment by mattstratton** [comment] 2016-08-26 16:59
We have moved from Wercker to Netlify, so this can be closed.

**Closed by mattstratton** 2016-08-26 16:59 UTC
Labels: in progress, workflow
