### ISSUE TITLE
Add a way for sponsors to know which conferences are open for sponsorship

### ISSUE THREAD

**Issue by quintessence** [devopsdays/devopsdays-web#8683] opened 2019-11-06 00:14 UTC
To help make it easier for prospective sponsors to tell which conferences are currently accepting sponsorships / have sponsorships defined, can we add a feature flag, page, Google Sheet, or something to the process?

**Comment by bridgetkromhout** [comment] 2019-11-06 09:40
We can’t easily predict when sponsorships will close (since they can fill unpredictably), so we can’t display a page like the speaking one that lists closing times. We can list what’s open now (in a single place, and/or on their pages).

**Comment by mattstratton** [comment] 2019-11-06 12:54
I think it’s not going to be terribly tough to make a list of ones that are open, based on the existing `sponsors_accepted` flag; i just would say that list won’t be truly comprehensive or accurate, but it’s Probably Fine™️

**Comment by quintessence** [comment] 2019-11-06 18:10
I think that should be Good Enough ™️.

Thought: could we automatically disable the `sponsor_accepted` flag on build, after an event has past? To help with clean up / when people remember to turn it on but not off.

**Comment by mattstratton** [comment] 2019-11-06 18:15
Naw. The page would only show upcoming events with that flag.

**Comment by quintessence** [comment] 2019-11-06 19:45
Excellent :D

**Comment by richardboydii** [comment] 2019-11-08 21:03
If "accepting_sponsors" == true, could we generate a view / page on build that would show what's currently open for sponsorships? 

Also: do we coordinate sponsorship at the DoD Org level across multiple events? Or is it feed yourself with sponsorship? For another conference I've organized one sponsor agreed to sponsor several city conferences in the family.

**Comment by bridgetkromhout** [comment] 2019-11-09 15:23
> If "accepting_sponsors" == true, could we generate a view / page on build that would show what's currently open for sponsorships?

Possibly, but since it's opt-in and end-times of availability will vary, we can't make the same kinds of correctness guarantees as the page that says "these are the available CFPs".

> Also: do we coordinate sponsorship at the DoD Org level across multiple events?

Every event has their own finances and sets their own sponsorship levels, including deciding what to offer to sponsors. So, the core team does not control or coordinate sponsorships.

**Comment by mattstratton** [comment] 2019-11-09 15:58
Yeah, I’m okay with making a page that lists available sponsorship events based on that flag although i would put some disclaimer words on the page to the effect that it might not be totally accurate.

**Comment by mattstratton** [comment] 2019-11-09 15:59
And i already agreed to create the page based on the existing flag earlier in this thread :)

**Comment by bridgetkromhout** [comment] 2019-11-10 01:33
See https://github.com/devopsdays/devopsdays-web/pull/8713 for some discussion/iteration.

**Comment by bridgetkromhout** [comment] 2019-11-11 13:15
@mattstratton said "One possible thought - perhaps have the link be to “/sponsor” for each city, and maybe additionally have the check for display be a) if sponsor accepted is set and b) there is a sponsor.md file (this is more work i know but possibly more useful?)"

This is a fine idea. It would require:

1) checking to see if sponsor.md exists
2) Linking to there instead of the welcome page if it does exist.

We still would want to default to the welcome page if sponsors are accepted and that file doesn't exist, as nobody is required to have a file on that path.

Also we might want to consider toggling the default to be not accepting sponsors and make sure people mindfully turn it on when they're actually ready to?

**Comment by mattstratton** [comment] 2019-11-11 13:31
> We still would want to default to the welcome page if sponsors are accepted and that file doesn't exist, as nobody is required to have a file on that path

One thing we could do is like what we do with the "register" and "propose" CTA buttons; there is a way to specify the URL for your registration page if it's not `/register`; we could add a data field for "sponsor" page (which would default to `/sponsor` if not set).

The more I think about this, the more that I wonder if there is just a lot of opportunity for enhancing the sponsorship data for an event. I think it's also potentially interesting to have an optional data field for the URL of a prospectus; we could add a shortcode to display the prospectus link as well, which we could add to the template for `sponsor.md` (it would only execute if there was a prospectus link set). 

Basically, the proposal I have in mind is make "sponsor" work the same way as "propose" and "register"; give it the following data fields which are similar to how propose and register work:

```
sponsor_date_start: # start accepting sponsorships. Leave blank if sponsorship is not open yet
sponsor_date_end: # close sponsorship. Leave blank if sponsorship is not open yet.

sponsorship_link: "" # If you have a custom sponsorship link, enter it here. This will control the Sponsor menu item as well as the "Sponsor" button.

```

We would keep `sponsors_accepted` for backwards compatibility, but it would only control the "become a ____ sponsor!" links as it does today, but if it's not set, the "become a ______ sponsor!' links would be controlled by the `sponsor_date_start` and `sponsor_date_end` fields.

We also would add a "sponsor" button to the Welcome page which is similar to the Register and Propose CTA buttons.

**Comment by bridgetkromhout** [comment] 2019-11-11 13:46
I don't think it's realistic to expect people to know when they're going to close all sponsorships (as I've seen emails horse-trading the day before an event starts!) - so unlike the propose and register elements, I personally wouldn't set that...?

**Comment by mattstratton** [comment] 2019-11-11 14:00
It’s optional :)

That being said, we could maybe not use the “closed” date at all, but only “turn off” sponsorship if sponsors accepted is set to’”off”; But then I’m not sure how having it “open” logic would work. 

I think that you can leave the “closed” date blank, but only set it if you WANT to close sponsorship.

Or we can remove the date fields and just use “sponsors accepted” but it defaults to “no” like you said. But if we add the other features it makes it more useful than just the “list of events with sponsorship”.

**Comment by quintessence** [comment] 2019-11-12 19:16
I wonder if we'll need that level of granularity? IIUC, once sponsorships are "turned on" they'll display until the day of the event on the page / endpoint, correct? If so, that might be Good Enough for v1, and then if it turns out that a little more granularity would be helpful, e.g. being able to manually disable pre-event, then it can be added then.

**Comment by mattstratton** [comment] 2019-11-12 19:27
Basically my intention is to have the experience for organizers be as similar as possible so it's not confusing. But I do think that setting it via "date" isn't quite what would be expected behavior. 

>Or we can remove the date fields and just use “sponsors accepted” but it defaults to “no” like you said. But if we add the other features it makes it more useful than just the “list of events with sponsorship”.

That's kind of the important part that I landed upon :)

**Comment by bridgetkromhout** [comment] 2019-12-09 23:22
@quintessence can you look at https://devopsdays.org/sponsor#which-events-have-sponsorship-opportunities-available-right-now and see if it meets the needs you envisioned when you opened this issue? Thanks.

**Comment by quintessence** [comment] 2019-12-10 17:35
oooo <3 

Looks like it'll work - thank you!

**Comment by bridgetkromhout** [comment] 2019-12-12 01:15
Great. @mattstratton can you either resolve this issue, or comment with what you'd like it to be about and rename it for clarity? Thanks!

**Comment by mattstratton** [comment] 2020-01-06 23:34
This looks pretty good - I'm happy with this for now.

**Closed by mattstratton** 2020-01-06 23:34 UTC
