### ISSUE TITLE
Paypal Image link contains extra content when rendered as html

### ISSUE THREAD

**Issue by timgifford** [devopsdays/devopsdays-web#6294] opened 2019-02-08 23:56 UTC
The source our sponsorship page is not rendering correctly. The image displays correctly on the markdown, however it contains extra code when rendered as HTML. I can't figure out where to look to fix it. It renders correctly when I run the hugo server locally.

Any help is appreciated.

Source: https://github.com/devopsdays/devopsdays-web/blob/master/content/events/2019-des-moines/sponsor.md (Line 93)
```
<a href="https://link.waveapps.com/nxpaye-gc84pw" target=”_blank”><img src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" /></a>
```
Rendered as:
```
<a href="https://link.waveapps.com/nxpaye-gc84pw" target="”_blank”"><img src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" srcset="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif 1x, https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG@2x.gif 2x"></a>
```
You can view the broken html code here: https://www.devopsdays.org/events/2019-des-moines/sponsor/

**Comment by MikeRosTX** [comment] 2019-02-09 00:23
Personally the way I would do it to avoid any headaches that can be caused by Paypal if they change their site, would be to download this [image](https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif?akam_redir=1) locally to your repo **sites/devopsdays-web/static/events/2019-des-moines** and point it to that image.

**Comment by MikeRosTX** [comment] 2019-02-09 17:05
Closing this issue.

**Closed by MikeRosTX** 2019-02-09 17:05 UTC
