### ISSUE TITLE
article:published_time (used by Slack and other apps) is unix epoch

### ISSUE THREAD

**Issue by kevinreedy** [devopsdays/devopsdays-web#1185] opened 2016-09-28 01:01 UTC
On https://www.devopsdays.org/events/2016-kansascity/program/kyle-sexton/, the meta information for published_time is the unix epoch (0001-01-01 00:00:00), which results in a bad date in apps that use this information.

```
<meta property="article:published_time" content="0001-01-01 00:00:00 &#43;0000 UTC"/>
```

<img width="957" alt="slack_-_chef" src="https://cloud.githubusercontent.com/assets/82251/18897148/26fbe994-84ed-11e6-9a80-d306fd65195e.png">

I also spot checked another link - https://www.devopsdays.org/events/2016-detroit/program/containers-will-not-fix/

**Comment by mattstratton** [comment] 2016-09-28 14:14
Oh, snap.

We set that here:
https://github.com/devopsdays/devopsdays-web/blob/master/layouts/partials/head/seo/open_graph.html#L36

But the problem is that `.PublishDate` isn't set in the frontmatter of anything.

One possible fix would be to change that line to be `content="{{ .Date }}` instead.

The other fix is to add the `PublishDate` parameter to frontmatter of everything.

I think that we should actually add `PublishDate`, because it might be used other places we don't know about. Or better yet, here's what we do:

1. Update the generators/archetypes to include `PublishDate`
2. put in a conditional to use `PublishDate` in the meta if it exists, and if not, use `Date`

**Comment by mattstratton** [comment] 2016-12-09 19:31
Did a little bit of digging, and it seems that `.PublishDate` is generated off of `Date`, but it's not working for some reason.

Hugo support forums suggested that the problem is we have `Date` in quotes, which is odd because it comes from the generator.

**Comment by mattstratton** [comment] 2017-01-30 17:54
This will be fixed in [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme)

**Closed by mattstratton** 2017-01-30 17:54 UTC
Labels: bug
