### ISSUE TITLE
Sponsor logo used when linking registration from Facebook

### ISSUE THREAD

**Issue by cobusbernard** [devopsdays/devopsdays-web#867] opened 2016-08-17 07:45 UTC
When you link your registration page, the `og:image` tag grabs the first image off the page via https://github.com/devopsdays/devopsdays-web/blob/master/layouts/partials/head/seo/open_graph.html#L6-L8

This makes it use your first sponsor logo for the post:
![screen shot 2016-08-17 at 9 44 05 am](https://cloud.githubusercontent.com/assets/591156/17728366/38859506-645f-11e6-9789-a96eff181459.png)

**Comment by phrawzty** [comment] 2016-08-17 09:37
That's an excellent observation. Any suggestions for a better behaviour?

**Comment by cobusbernard** [comment] 2016-08-17 09:39
Easy fix would to just have a default DOD image in there. Slightly more complex one would be to make it a value in the conf data file that defaults to a DOD image if you don't specify. Will play around with it later today and send a PR.

**Comment by mattstratton** [comment] 2016-08-17 12:12
This might be a dupe of https://github.com/devopsdays/devopsdays-web/issues/422

**Comment by mattstratton** [comment] 2016-08-17 12:19
In fact, it IS a dupe of #422. 

FYI, the code that does this is here:

https://github.com/devopsdays/devopsdays-web/blob/master/layouts/partials/head/seo/open_graph.html

It's taken from some partials by a Hugo community member, so we need to think about upstream fixes before hacking that file too badly, but It's Probably Fine. 

Anyway, let's raccoon this over to #422. Good catch on this one though!

**Closed by mattstratton** 2016-08-17 12:19 UTC
